repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
    - id: end-of-file-fixer
    - id: check-yaml
  # ----- Python formatting -----
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.1.13
  hooks:
      # Run ruff linter.
  - id: ruff
    args:
    - --quiet
    - --fix
      # Run ruff formatter.
  - id: ruff-format
