repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]
  - id: end-of-file-fixer
  - id: check-yaml
  # ----- Python formatting -----
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.10
  hooks:
      # Run ruff linter.
  - id: ruff
    args:
    - --quiet
    - --fix
      # Run ruff formatter.
  - id: ruff-format
  # ----- repo maintenance -----
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.14.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
- repo: https://github.com/tox-dev/pyproject-fmt
  rev: v2.5.1
  hooks:
  - id: pyproject-fmt
- repo: https://github.com/abravalheri/validate-pyproject
  rev: v0.24.1
  hooks:
  - id: validate-pyproject
